### ISSUE TITLE
Featured Article Bug

### ISSUE THREAD

**Issue by Joomlaplates** [JoomBoost/Joomla-Astroid-Framework#1]
Joomla 4.0.3 and Template One with Astroid 2.5.4
The Featured Article view ignore the columns (2) when Leading Article is set to 1 ( see pictiúre attched)
**Ok I found the issue, its a bug in the file >**
\html\com_content\featured\default.php ( line 50)

**Wrong code.**
```
<?php
$introcount = (count($this->intro_items));
$counter = 0;
$columns = ASTROID_JOOMLA_VERSION > 3 ? 1 : $this->columns;
?>
```

**Fixed Code**
```
<?php
$introcount = (count($this->intro_items));
$counter = 0;
$columns = ASTROID_JOOMLA_VERSION > 3 ? $this->params->get('num_columns', 1) : $this->columns;
?>
```
![Screenshot_2-2-3-4](https://user-images.githubusercontent.com/71080509/133674783-7731c129-0b6a-4b45-b4e7-cfa2e581a377.jpg)

**Comment by andiamine** [comment]
Fixed, thanks
