### ISSUE TITLE
the style sheet no longer exists

### ISSUE THREAD

**Issue by fontanil** [JoomBoost/Joomla-Astroid-Framework#3]
Hello,

The actual version 2.5.4 of Astroid is adding a Cassiopeia file that no longer exists.
In libraries/astroid/framework/library/astroid/Helper/Head.php line 62:
`$document->addStyleSheet('templates/cassiopeia/css/vendor/fontawesome-free/fontawesome.min.css');`

Regards,
Robert

**Comment by andiamine** [comment]
Fixed in commit https://github.com/JoomBoost/Joomla-Astroid-Framework/commit/c5069adf49d5ae9339948ab1004a6e3626553325
