### ISSUE TITLE
Pagination in mobile view runs out of screen

### ISSUE THREAD

**Issue by Joomlaplates** [JoomBoost/Joomla-Astroid-Framework#4]
Hello, 
the article Pagination in mobile view runs out of screen.
See image attached
![pagination](https://user-images.githubusercontent.com/71080509/139307857-9d1e4915-cccf-4791-9e24-175b6f9a1a19.jpg)

**Old code**
```
.pagination {
    display: flex;
    padding-left: 0;
    list-style: none;
    border-radius: 0.25rem;
}
```

**Fixed Code**
```
.pagination {
    display: flex;
    padding-left: 0;
    list-style: none;
    border-radius: 0.25rem;
    flex-wrap: wrap;
}
```

I think this css code comes from Bootstrap

**Comment by andiamine** [comment]
done in commit https://github.com/JoomBoost/Joomla-Astroid-Framework/commit/7bd1ba1648a956b5ee0eee1d3f16f21582218522
