### ISSUE TITLE
Remove Template One ?

### ISSUE THREAD

**Issue by darekmer** [JoomBoost/Joomla-Astroid-Framework#7]
Hello, you want to remove Template One, really ?
It is nicer than Template Zero.

**Comment by andiamine** [comment]
Hi my friend, i think Template One has less module positions and lightweight structure, zero template is more complete , am i right ?

**Comment by fontanil** [comment]
Hello,
Personally I almost never use Zero, I prefer One. And it's easy to add/change the layout and add positions in the module management, so the number of module positions is not a problem.

**Comment by andiamine** [comment]
thanks for clarifications, i think we are going to support both templates.
